# Generated by Django 5.1.7 on 2025-10-01 14:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del cliente')),
                ('encargado', models.CharField(max_length=200, verbose_name='Persona encargada')),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presupuesto disponible')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('fecha_vencimiento_presupuesto', models.DateField(verbose_name='Fecha de vencimiento del presupuesto')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaProveedora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('encargado', models.CharField(max_length=200, verbose_name='Persona encargada')),
            ],
            options={
                'verbose_name': 'Empresa Proveedora',
                'verbose_name_plural': 'Empresas Proveedoras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pedido')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado del pedido')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del pedido')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='SippApp.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='ProductoHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del productos')),
                ('tipo', models.CharField(choices=[('switch', 'Switch'), ('disco_duro', 'Disco Duro'), ('ram', 'RAM'), ('impresora', 'Impresora'), ('teclado', 'Teclado'), ('mouse', 'Mouse'), ('ordenador', 'Ordenador'), ('laptop', 'Laptop'), ('otros', 'Otros')], max_length=100, verbose_name='Tipo de productos')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('activo', models.BooleanField(default=True, verbose_name='Producto disponible')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SippApp.categoriaproducto', verbose_name='Categoría')),
                ('empresa_proveedora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='SippApp.empresaproveedora', verbose_name='Empresa Proveedora')),
            ],
            options={
                'verbose_name': 'Producto de Hardware',
                'verbose_name_plural': 'Productos de Hardware',
                'ordering': ['tipo', 'nombre'],
                'unique_together': {('nombre', 'empresa_proveedora')},
            },
        ),
        migrations.CreateModel(
            name='CaracteristicaProductoHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=200)),
                ('producto_hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='SippApp.productohardware', verbose_name='Producto de Hardware')),
            ],
            options={
                'verbose_name': 'Caracteristica de Producto de Hardware',
            },
        ),
        migrations.CreateModel(
            name='ServicioInformatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del servicio')),
                ('duracion', models.PositiveIntegerField(verbose_name='Duración del servicio')),
                ('unidad_duracion', models.CharField(choices=[('horas', 'Horas'), ('dias', 'Días'), ('meses', 'Meses')], max_length=10, verbose_name='Unidad de duración')),
                ('descripcion', models.TextField(verbose_name='Descripción del servicio')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio del servicio')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones generales')),
                ('activo', models.BooleanField(default=True, verbose_name='Servicio disponible')),
                ('empresa_proveedora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='SippApp.empresaproveedora', verbose_name='Empresa Proveedora')),
            ],
            options={
                'verbose_name': 'Servicio Informático',
                'verbose_name_plural': 'Servicios Informáticos',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'empresa_proveedora')},
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='SippApp.servicioinformatico', verbose_name='Servicio Informatico')),
            ],
            options={
                'verbose_name': 'Tipo Servicio',
            },
        ),
        migrations.CreateModel(
            name='ItemProductoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_productos', to='SippApp.pedido')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SippApp.productohardware', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Item de Producto en Pedido',
                'verbose_name_plural': 'Items de Productos en Pedidos',
                'unique_together': {('pedido', 'productos')},
            },
        ),
        migrations.CreateModel(
            name='ItemServicioPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_servicios', to='SippApp.pedido')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SippApp.servicioinformatico', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Item de Servicio en Pedido',
                'verbose_name_plural': 'Items de Servicios en Pedidos',
                'unique_together': {('pedido', 'servicio')},
            },
        ),
    ]
