# Generated by Django 5.1.7 on 2025-10-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SippApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productohardware',
            name='tipo_personalizado',
            field=models.CharField(blank=True, max_length=100, verbose_name="Tipo personalizado (si selecciona 'Otros')"),
        ),
        migrations.AlterField(
            model_name='productohardware',
            name='tipo',
            field=models.CharField(choices=[('switch', 'Switch'), ('disco_duro', 'Disco Duro'), ('ram', 'RAM'), ('impresora', 'Impresora'), ('teclado', 'Teclado'), ('mouse', 'Mouse'), ('ordenador', 'Ordenador'), ('laptop', 'Laptop'), ('otros', 'Otros')], default='otros', max_length=100, verbose_name='Tipo de productos (selección)'),
        ),
    ]
