# Generated by Django 5.1.7 on 2025-10-01 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SippApp', '0002_productohardware_tipo_personalizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productohardware',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SippApp.categoriaproducto', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='productohardware',
            name='empresa_proveedora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='SippApp.empresaproveedora', verbose_name='Empresa Proveedora'),
        ),
    ]
