# Generated by Django 5.2.6 on 2025-10-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SippApp', '0004_alter_productohardware_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemproductopedido',
            old_name='productos',
            new_name='producto',
        ),
        migrations.AlterUniqueTogether(
            name='itemproductopedido',
            unique_together={('pedido', 'producto')},
        ),
    ]
